<?php
namespace Teeparty\Task;

use Teeparty\Job;
use Teeparty\Task;

class Factory {

    /**
     * Create a new task.
     * 
     * @param string $job job class.
     * @param array $context context to run job in.
     * @param string $id task id.
     *
     * @return Task A new Task.
     */
    public static function create($job, array $context = array(), $id = null)
    {
        if (!($job instanceof Job)) {
            if (!class_exists($job)) {
                throw new Exception('unknown class: ' . $job);
            }

            $w = new $job;
        } else {
            $w = $job;
        }

        if (!$w instanceof Job) {
            throw new Exception($job.' must implement \Teeparty\Task\Job');
        }
        
        $c = new Context($context);
        return new Task($w, $c, $id);
    }


    /**
     * Create a new task from the given array.
     *
     * The following keys are available:
     *
     *  - job: The className of the job.
     *  - context [optional]: key-value dict with job arguments (empty 
     *                        by default).
     *  - id [optional]: task id to use (auto-generated by default).
     *
     * @param array $data task information.
     * @return Task A new task.
     */
    public static function createFromArray(array $data)
    {
        if (is_array($data['context']) || is_object($data['context'])) {
            $context = (array) $data['context']; 
        } else {
            $context = array();
        }
        
        $task = self::create(
            $data['job'], 
            $context,
            isset($data['id']) ? $data['id'] : ''
        );
        
        return $task;
    }


    public static function createFromMessage($msg)
    {
        return self::createFromArray((array) $msg);
    }
}
